name: flutter_password_generator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  material_color_generator: ^1.1.0

dev_dependencies:
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_app_name:
  name: 'Password Generator'
flutter_icons:
  android: 'launcher_icon'
  ios: true
  remove_alpha_ios: true
  image_path: 'lib/assets/images/password_generator_launcher_icon.png'

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
